# Generated by Django 5.1.5 on 2025-01-16 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nombres y apellidos')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la empresa (Razón social)')),
                ('commercial_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre comercial (Opcional)')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web (Opcional)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio de operaciones')),
                ('company_type', models.CharField(blank=True, choices=[('individual', 'Individual/Propietario Único o LLC de un solo miembro'), ('corporation_c', 'Corporación C'), ('corporation_s', 'Corporación S'), ('association', 'Asociación'), ('trust', 'Fideicomiso/Patrimonio'), ('none', 'Ninguna opción aplica')], max_length=20, verbose_name='Tipo de empresa')),
                ('transaction_purpose', models.TextField(blank=True, verbose_name='Objetivo de las transacciones')),
                ('annual_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Volumen anual de transacciones (en USD)')),
                ('annual_transactions', models.IntegerField(default=0, verbose_name='Número anual de transacciones')),
                ('currencies_needed', models.CharField(blank=True, max_length=255, verbose_name='Divisas requeridas')),
                ('payment_method', models.CharField(blank=True, choices=[('ach', 'ACH Débito Directo'), ('check', 'Cheque'), ('transfer', 'Transferencia'), ('none', 'No aplicable')], max_length=20, verbose_name='Método preferido de pago')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del banco')),
                ('bank_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección del banco')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('routing_number', models.CharField(blank=True, max_length=50, verbose_name='Número ABA/Código de ruta')),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Cheques'), ('savings', 'Ahorros')], max_length=20, verbose_name='Tipo de cuenta')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Registro completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombres y apellidos')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo en la empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Authorized User',
                'verbose_name_plural': 'Authorized Users',
            },
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Nombre legal (sin abreviaciones)')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de propiedad')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Partner',
                'verbose_name_plural': 'Company Partners',
            },
        ),
    ]
